# Generated by Django 6.0.1 on 2026-02-04 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holeapp', '0002_alter_product_est_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campany', to='Holeapp.company'),
        ),
    ]
