# Generated by Django 6.0.1 on 2026-02-04 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Holeapp', '0003_alter_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='Head_quater',
            new_name='head_quater',
        ),
    ]
