# Generated by Django 6.0.1 on 2026-02-04 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Holeapp', '0004_rename_head_quater_company_head_quater'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Name',
            new_name='name',
        ),
    ]
