# Generated by Django 6.0.1 on 2026-02-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holeapp', '0005_rename_name_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_img',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
