# Generated by Django 6.0.1 on 2026-02-06 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holeapp', '0006_product_prod_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='advantage',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
