# Generated by Django 6.0.1 on 2026-02-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holeapp', '0007_product_advantage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='advantage',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
