# Generated by Django 6.0.1 on 2026-02-06 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holeapp', '0008_alter_product_advantage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Holeapp.company'),
        ),
    ]
