# Generated by Django 6.0.1 on 2026-02-09 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holeapp', '0009_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campany', to='Holeapp.company'),
        ),
        migrations.CreateModel(
            name='ExteriorImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inte_img', models.ImageField(blank=True, null=True, upload_to='exteriorimg/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extproducts', to='Holeapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='InteriorImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inte_img', models.ImageField(blank=True, null=True, upload_to='interiorimg/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intproducts', to='Holeapp.product')),
            ],
        ),
    ]
